spring.application.name=POS-system

server.port=${PORT:8081}

# Database Configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}

server.error.include-message=always

app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}